# Generated by Django 3.2.3 on 2021-06-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postbk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='photo',
            new_name='Upload_photo',
        ),
    ]
